# Copyright 2014 Dextra, all rights reserved

option(WITH_POCO "Use Poco Library for Regular Expressions" OFF)
option(WITH_PCRE "Use PCRE Library for Regular Expressions" OFF)
option(WITH_TESTS "Build Tests" ON)

macro(find_poco)
	if(NOT POCO_FOUNDATION_LIBRARIES)
		find_library(POCO_FOUNDATION_LIBRARIES PocoFoundation)
		if(POCO_FOUNDATION_LIBRARIES)
			message(STATUS "Using Poco Library for Regular Expressions")
		endif(POCO_FOUNDATION_LIBRARIES)
	endif(NOT POCO_FOUNDATION_LIBRARIES)
endmacro(find_poco)
macro(find_pcre)
	find_package(PCRE)
	if(PCRE_FOUND AND NOT PCRE_FIND_QUIETLY)
		message(STATUS "Using PCRE Library for Regular Expressions")
	endif(PCRE_FOUND AND NOT PCRE_FIND_QUIETLY)
endmacro(find_pcre)

# If neither was chosen, try PCRE first and then POCO
if(NOT WITH_POCO AND NOT WITH_PCRE)
	find_pcre()
	if(PCRE_FOUND)
		set(WITH_PCRE ON)
	else(PCRE_FOUND)
		find_poco()
		if(NOT POCO_FOUNDATION_LIBRARIES)
			message(FATAL_ERROR "Neither Poco nor PCRE libraries available")
		else(NOT POCO_FOUNDATION_LIBRARIES)
			set(WITH_POCO ON)
		endif(NOT POCO_FOUNDATION_LIBRARIES)
	endif(PCRE_FOUND)
endif(NOT WITH_POCO AND NOT WITH_PCRE)

set(REGEXP_EXTRA_SRC)
if(WITH_PCRE)
	if(NOT PCRE_FOUND)
		find_pcre()
	endif(NOT PCRE_FOUND)
	if(NOT PCRE_FOUND)
		message(FATAL_ERROR "PCRE Library not found!")
	endif(NOT PCRE_FOUND)
	# PCRE found
	set(REGEXP_LIBRARY ${PCRE_LIBRARIES})
	set(REGEXP_EXTRA_SRC ${REGEXP_EXTRA_SRC} "poco_regexp.cpp")
else(WITH_PCRE)
	if(WITH_POCO)
		if(NOT POCO_FOUNDATION_LIBRARIES)
			find_poco()
		endif(NOT POCO_FOUNDATION_LIBRARIES)
		if(NOT POCO_FOUNDATION_LIBRARIES)
			message(FATAL_ERROR "Poco Library not found!")
		endif(NOT POCO_FOUNDATION_LIBRARIES)
		# Poco found
		set(REGEXP_LIBRARY ${POCO_FOUNDATION_LIBRARIES})
	endif(WITH_POCO)
endif(WITH_PCRE)

