#ifndef __BACKEND_SHARED_H__
#define __BACKEND_SHARED_H__

#define COMMAND_COPY_TAB_DELIMITED "T"
#define COMMAND_COPY_CSV_SEMICOLON_TO_TEMP_TABLE "S"
#define COMMAND_COPY_KEY_VALUE "K"

#endif // __BACKEND_SHARED_H__
